---
- name: Create an ELB for the kubernetes master instance to proxy the apiserver service
  local_action:
    module: ec2_elb_lb
    region: "{{ region }}"
    name: "{{ k8s_cluster }}-apiserver-elb"
    scheme: internal
    state: present
    security_group_names: "{{ master_security_group }}"
    instance_ids: "{{ _ec2_master.results |map(attribute='instance_ids.0') |list}}"
    tags:
      KubernetesCluster: "{{ k8s_cluster }}"
    subnets: "{{ _subnet.results | selectattr('item.route', 'equalto', 'Public') | map(attribute='subnet.id') | list }}"
    listeners:
      - protocol: http
        load_balancer_port: 8080
        instance_port: 8080

      - protocol: tcp
        load_balancer_port: 6443
        instance_port: 6443
  when: _ec2_master.changed == true
  tags:
    - elb
