---

- name: Create a NAT instance security group
  ec2_group:
    name: "{{ nat_security_group }}"
    description: an kubernetes nat security group
    vpc_id: "{{ _vpc.vpc.id}}"
    region: "{{ region }}"
    rules:
      # 'ports' rule keyword was introduced in version 2.4. It accepts a single port value or a list of values including ranges (from_port-to_port).
      - proto: all
        cidr_ip: "{{ vpc.cidr_block }}"
  register: _nat_sg

- name: Create a kubernetes master security group
  ec2_group:
    name: "{{ master_security_group }}"
    description: an kubernetes master security group
    vpc_id: "{{ _vpc.vpc.id}}"
    region: "{{ region }}"
    rules:
      # 'ports' rule keyword was introduced in version 2.4. It accepts a single port value or a list of values including ranges (from_port-to_port).
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      # Rule sources list support was added in version 2.4. This allows to define multiple sources per source type as well as multiple source types per rule.
      - proto: all
        cidr_ip: "{{ vpc.cidr_block }}"

      - proto: all
        group_name: "{{ k8s_cluster }}_master_sg"
  register: _master_sg

- name: Create a kubernetes node security group
  ec2_group:
    name: "{{ node_security_group }}"
    description: an kubernetes node security group
    vpc_id: "{{ _vpc.vpc.id }}"
    region: "{{ region }}"
    rules:
      # 'ports' rule keyword was introduced in version 2.4. It accepts a single port value or a list of values including ranges (from_port-to_port).
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0

      - proto: all
        cidr_ip: "{{ vpc.cidr_block }}"

      - proto: all
        group_name: "{{ k8s_cluster }}_node_sg"
  register: _node_sg

- name: Add tag to master security group
  ec2_tag:
    region: "{{ region }}"
    resource: "{{ _master_sg.group_id }}"
    state: present
    tags:
      Name: "{{ k8s_cluster }}_master_sg"
      KubernetesCluster: "{{ k8s_cluster }}"


- name: Add tag to node security group
  ec2_tag:
    region: "{{ region }}"
    resource: "{{ _node_sg.group_id }}"
    state: present
    tags:
      Name: "{{ k8s_cluster }}_node_sg"
      KubernetesCluster: "{{ k8s_cluster }}"

- name: Add tag to NAT security group
  ec2_tag:
    region: "{{ region }}"
    resource: "{{ _nat_sg.group_id }}"
    state: present
    tags:
      Name: "{{ k8s_cluster }}_nat_sg"
      KubernetesCluster: "{{ k8s_cluster }}"
