---

# export KUBE_APISERVER="https://172.20.0.113:6443"
- name: Create kubelet bootstrapping kubeconfig
  shell: "{{ item }}"

  with_items:
    - >-
      kubectl config set-cluster kubernetes
      --certificate-authority=/etc/kubernetes/ssl/ca.pem --embed-certs=true 
      --server=${KUBE_APISERVER}  --kubeconfig=bootstrap.kubeconfig
    - >- 
      kubectl config set-credentials kubelet-bootstrap 
      --token={{BOOTSTRAP_TOKEN}} --kubeconfig=bootstrap.kubeconfig
    - >- 
      kubectl config set-context default 
      --cluster=kubernetes --user=kubelet-bootstrap 
      --kubeconfig=bootstrap.kubeconfig
    - kubectl config use-context default --kubeconfig=bootstrap.kubeconfig


- name: Create kube-proxy bootstrapping kubeconfig
  shell: "{{ item }}"
  with_items:
    - >- 
      kubectl config set-cluster kubernetes  
      --certificate-authority=/etc/kubernetes/ssl/ca.pem 
      --embed-certs=true --server=${KUBE_APISERVER} 
      --kubeconfig=kube-proxy.kubeconfig
    - >- 
      kubectl config set-credentials kube-proxy 
      --client-certificate=/etc/kubernetes/ssl/kube-proxy.pem 
      --client-key=/etc/kubernetes/ssl/kube-proxy-key.pem 
      --embed-certs=true --kubeconfig=kube-proxy.kubeconfig
    - >-
      kubectl config set-context default 
      --cluster=kubernetes --user=kube-proxy --kubeconfig=kube-proxy.kubeconfig
    - kubectl config use-context default --kubeconfig=kube-proxy.kubeconfig
