---
- name: restart kubelet
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted

- name: restart kube-proxy
  systemd:
    name: kube-proxy
    daemon_reload: yes
    state: restarted

- name: restart nginx-proxy
  systemd:
    name: nginx-proxy
    daemon_reload: yes
    state: restarted
